config/routes.rb
Redrhinomail::Application.routes.draw do

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

    namespace :settings do
    resources :companies
    resources :lists
    end
  root :to => "dashboards#show"

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :users
	has_many :lists

	validates_presence_of :name, :phone
	validates_uniqueness_of :name

end

app/models/list.rb
class List < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation, :role_id

  attr_accessor :password
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  belongs_to :company
  belongs_to :role


  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end
  
  def new_random_password
    self.password= Base64.encode64(Digest::SHA1.digest("#{rand(1<<64)}/#{Time.now.to_f}/#{Process.pid}"))[0..7]
    self.password_confirmation = self.password
  end

  private
  
  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ControllerAuthentication
  protect_from_forgery
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  before_filter :login_required
  def show
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:login], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to_target_or_default root_url, :notice => "Logged in successfully."
    else
      flash.now[:alert] = "Invalid login or password."
      render :action => 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "You have been logged out."
  end
end

app/controllers/settings/companies_controller.rb
class Settings::CompaniesController < ApplicationController
   before_filter :login_required
   before_filter :get_company
    def show

  end

  def edit

  end

  def update
    if @company.update_attributes(params[:company])
      redirect_to settings_company_url, :notice => 'Company was updated successfully!'
    else
      render :edit
    end
  end

  private
  def get_company
     @company = current_user.company
  end
end

app/controllers/settings/lists_controller.rb
class Settings::ListsController < ApplicationController
   before_filter :login_required
   before_filter :get_list
    def index

  end

  def edit

  end

  def update
    if @list.update_attributes(params[:list])
      redirect_to settings_list_url, :notice => 'List was updated successfully!'
    else
      render :edit
    end
  end

  private
  def get_list
     @list = current_user.list
  end
end

app/controllers/settings/requires_authentication.rb
class RequiresAuthentication < ApplicationController
	before_filter :login_required
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :except => [:new, :create]
   def index
	  @users = current_user.company.users
  end
  def new
    @user =  User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Thank you for signing up! You are now logged in."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Your profile has been updated."
    else
      render :action => 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/settings/companies_helper.rb
module Settings::CompaniesHelper
end

app/helpers/settings/lists_helper.rb
module Settings::ListsHelper
end

app/helpers/settings/requires_authentication_helper.rb
module Settings::RequiresAuthenticationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboards/show.html.erb
<h1>Dashboards#show</h1>
<p>Find me in app/views/dashboards/show.html.erb</p>

app/views/layouts/application.html.erb
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="no-js ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<html>
	<head>
		<meta charset="utf-8">

		<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame
	       Remove this if you use the .htaccess -->
	  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	
	
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

		<meta name="description" content="">
	  <meta name="author" content="NexBusiness LLC, Cade Cote">


    <%= stylesheet_link_tag "style" %>
    <%= javascript_include_tag'libs/modernizr-1.7.min.js' %>
	  
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
		<% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>

		<div id="container">
	    <header>
				<% if current_user %>
				<div class="company-name"><%= current_user.company.name %></div>
				<% end %>
				<ul class="navigation">
					<li><%= link_to 'Dashboard', root_url %></li>
					<li><a href="#">Settings</a>
						<div class="submenu">
							<ul>
								<li><%= link_to 'Users', users_url %></li>
								<li><%= link_to 'Company', settings_companies_url %></li>
                                <li><%= link_to 'Lists', settings_lists_url %></li>
							</ul>
						</div>
					</li>

				</ul>
	    </header>
			<section class="content-area">
				<%= yield %>
			</section>
	  </div>
	
		<!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if necessary -->
	   <%= javascript_include_tag :defaults %>
	
	
		<!--[if lt IE 7 ]>
	    <script src="javascripts/libs/dd_belatedpng.js"></script>
	    <script>DD_belatedPNG.fix("img, .png_bg"); // Fix any <img> or .png_bg bg-images. Also, please read goo.gl/mZiyb </script>
	  <![endif]-->
			
		<%= yield :javascript%>
  </body>
</html>

app/views/settings/companies/edit.html.erb
<h1>Edit: <%= @company.name %></h1>

<%= form_for [:settings, @company], :html => { :multipart => true }   do |f| %>
	<%= f.error_messages %>
	<div class="fields">
		<%= f.label :name, 'Company Name' %>
		<%= f.text_field :name %>
	</div>
	<div class="fields">
		<%= f.label :phone %>
		<%= f.text_field :phone %>
	</div>
	
	<div class="fields">
		<%= f.label :website %>
		<%= f.text_field :website %>
	</div>
	<div class="buttons">
		<%= f.submit 'Update' %>
	</div>
<% end %>

app/views/settings/companies/index.html.erb
<h1><%= @company.name %></h1>
<div class="actions"><%= link_to 'Edit', edit_settings_company_url(@company) %></div>

app/views/settings/lists/edit.html.erb
<h1>Edit: <%= @list.name %></h1>

<%= form_for [:settings, @list], :html => { :multipart => true }   do |f| %>
	<%= f.error_messages %>
	<div class="fields">
		<%= f.label :name, 'List Name' %>
		<%= f.text_field :name %>
	</div>
	<div class="fields">
		<%= f.label :is_active %>
		<%= f.check_box :is_active %>
	</div>
	<div class="buttons">
		<%= f.submit 'Update' %>
	</div>
<% end %>

app/views/settings/lists/index.html.erb
<h1><%= @list.name %></h1>
<div class="actions"><%= link_to 'Edit', edit_settings_lists_url(@list) %></div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit (@user.new_record? ? "Sign up" : "Update") %></p>
<% end %>

app/views/users/edit.html.erb
<% title "Update Profile" %>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>
<% if is_admin? %>
	<%= link_to 'New User', new_user_url%>
<% end %>
<table>
	<tr>
		<th>Username</th>
		<th>Email</th>
		<th></th>
	<tr>
<% @users.each do |u| %>
	<tr>
		<td><%= u.username %></td>
		<td><%= u.email %></td>
		<% if is_admin? %>
			<td><%= link_to 'Edit', edit_user_url(u) %></td>
		<% end %>
	</tr>
<% end %>
</table>

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>